# Generated by Django 4.2.7 on 2023-12-02 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id_instalacoes', models.AutoField(primary_key=True, serialize=False)),
                ('pedido', models.CharField(max_length=20)),
                ('vendedor', models.TextField(max_length=100)),
                ('metragem', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_criacao', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
